### ISSUE TITLE
Missing RIS data fields

### ISSUE THREAD

**Issue by akorinek** [hash-bang/RefLib#7]
I downloaded this .ris file from Google Scholar.

Seems like the Authors are encoded as A1 and the journal as JO. Can you please update the driver to read those fields?

TY  - JOUR
T1  - Insights into the molecular architecture of the 26S proteasome
A1  - Nickell, Stephan
A1  - Beck, Florian
A1  - Scheres, Sjors HW
A1  - Korinek, Andreas
A1  - Förster, Friedrich
A1  - Lasker, Keren
A1  - Mihalache, Oana
A1  - Sun, Na
A1  - Nagy, István
A1  - Sali, Andrej
JO  - Proceedings of the National Academy of Sciences
VL  - 106
IS  - 29
SP  - 11943
EP  - 11947
SN  - 0027-8424
Y1  - 2009
PB  - National Acad Sciences
ER  -

**Comment by hash-bang** [comment]
Hmm. It seems that Google Scholar is not adding the extra 2 space characters after the field definition (if you add that in it works).

I'll adjust the driver to cope with variable spacing.

**Comment by hash-bang** [comment]
Ok, I've tweaked the source code somewhat and added your specific case into the testkit.

It should be able to read Googles RIS format now.

**Comment by akorinek** [comment]
Thanks, you forgot to commit the changes though :-)

**Comment by hash-bang** [comment]
Ah sorry, the changes I made were in the Node version of the RefLib library not the PHP version.

[Reflib-RIS](https://github.com/hash-bang/reflib-ris) @ 1.0.6

I'll mark this module as depreciated as I don't really update it any more. Sorry, unless you want to push a PR I doubt this will be fixed.
